# -*- coding: utf-8 -*-
"""bands_split.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iEk7Jvr8E4Dwd5IM1V0K0YsOWbzwRO0B

#BANDS SPLIT one image
in questo notebook si implementa il codice per estrarre le 4 bande delle immagini png, ottenute dopo il crop delle imamgini scaricate da Google Earth Pro.



---



---



1.   Google Drive viene montato per poter accedere e salvare i file.
2.   L'immagine PNG viene aperta con PIL.Image.open().
3.  Le quattro bande vengono estratte usando image.split().
4. Si crea automaticamente una cartella in Google Drive per i file elaborati.
5. Le immagini delle bande vengono salvate in PNG, formato lossless adatto per conservare i dati senza perdita di qualità.


---



---
"""

# Import necessari
import os
from PIL import Image
from google.colab import drive

# 1. Monta Google Drive
drive.mount('/content/drive')

# 2. Specifica il percorso dell'immagine originale
image_path = "/content/drive/MyDrive/Colab Notebooks/Mat4Pat/GEP/Kenya/cropped/201812_cropped.png"
# 3. Carica l'immagine
image = Image.open(image_path)

# 4. Estrai le bande (Red, Green, Blue, Alpha)
r, g, b, a = image.split()

# 5. Crea il nome della cartella per salvare le bande
image_name = os.path.basename(image_path).split(".")[0]  # "201901_cropped"
output_folder = f"/content/drive/MyDrive/Colab Notebooks/Mat4Pat/GEP/Kenya/bands/{image_name}_bands"
os.makedirs(output_folder, exist_ok=True)  # Crea la cartella se non esiste

# 6. Salva le bande in formato PNG
r.save(os.path.join(output_folder, f"{image_name}_red.png"))
g.save(os.path.join(output_folder, f"{image_name}_green.png"))
b.save(os.path.join(output_folder, f"{image_name}_blue.png"))
#a.save(os.path.join(output_folder, f"{image_name}_alpha.png"))

print(f"Le bande sono state salvate nella cartella: {output_folder}")

"""#BANDS SPLIT function

Funzione: extract_and_save_bands
Questa funzione:

Accetta il percorso di una cartella in Google Drive contenente le immagini PNG.
Per ogni immagine nella cartella:
Estrae le bande (Rosso, Verde, Blu, Alfa).
Crea una cartella separata per ogni immagine.
Salva le quattro bande in formato PNG nella rispettiva cartella.

---



---


Crea una cartella in Google Drive con le immagini PNG che vuoi elaborare.
Aggiorna i percorsi in input_folder e output_folder con i tuoi percorsi reali.
Esegui il codice in Google Colab.
Le bande saranno salvate in sottocartelle separate, una per ogni immagine elaborata.


---



---
"""

from google.colab import drive
drive.mount('/content/drive')

import os
from PIL import Image

# Specificare il percorso della cartella con le immagini su Google Drive
input_folder = "/content/drive/MyDrive/Colab Notebooks/Mat4Pat/GEP/Kenya/cropped"

# Specificare il percorso della cartella in cui salvare i risultati
output_base_folder = "/content/drive/MyDrive/Colab Notebooks/Mat4Pat/GEP/Kenya/bands"

# Creare la cartella di output se non esiste
os.makedirs(output_base_folder, exist_ok=True)

def extract_and_save_bands(image_path, image_name, output_base_folder):
    try:
        # Carica l'immagine
        image = Image.open(image_path)

        # Estrai le bande (Rosso, Verde, Blu, Alfa)
        r, g, b, a = image.split()

        # Crea il nome della cartella per salvare le bande
        image_name = image_name.split('.')[0] # Rimuove ".png"
        output_folder = os.path.join(output_base_folder, f"{image_name}_bands")
        os.makedirs(output_folder, exist_ok=True)

        # Salva le bande in PNG
        r.save(os.path.join(output_folder, f"{image_name}_red.png"))
        g.save(os.path.join(output_folder, f"{image_name}_green.png"))
        b.save(os.path.join(output_folder, f"{image_name}_blue.png"))
        #a.save(os.path.join(output_folder, f"{image_name}_alpha.png"))

        print(f"Elaborata: {image_name} -> Bande salvate in {output_folder}")

    except Exception as e:
        print(f"Errore con {image_name}: {e}")

# Ottenere la lista delle immagini nella cartella
image_files = [f for f in os.listdir(input_folder) if f.endswith((".png"))]

# Elaborare tutte le immagini
for image_file in image_files:
    image_path = os.path.join(input_folder, image_file)
    extract_and_save_bands(image_path, image_file, output_base_folder)