# -*- coding: utf-8 -*-
"""Image_Cropper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ucbl3WwSckTC0hJAk5PHdZV5POs_BrUQ

#Cropp di immagini satellitari in formato jpg

In questo notebook, data un'immagine jpg e date le 4 coordinate pixel, si ritaglia l'immagine al solo riquadro di interesse.
Per selezionare i 4 vertici del poligono da ritagliare si utilizza lo script python "seleziona_punti.py".
"""

from PIL import Image, ImageDraw
import os

# Punti del poligono (in ordine)
#P1 = (1930, 435)
#P2 = (5297, 435)
#P3 = (5297, 4474)
#P4 = (1930, 4474)

P1 = (305, 594)
P2 = (1954, 594)
P3 = (1954, 1262)
P4 = (305, 1262)

'''
P1 = (2550, 170)
P2 = (6200, 170)
P3 = (6200, 4270)
P4 = (2550, 4270)'''


polygon_points = [P1, P2, P3, P4]  # Assicurati che siano in ordine (antiorario o orario)

# Definisci la funzione per ritagliare un'immagine in base ai punti del poligono
def crop_image_with_polygon(image_path, points, output_dir):
    # Carica l'immagine
    image = Image.open(image_path)

    # Creare una maschera con lo stesso formato e dimensione dell'immagine
    mask = Image.new("L", image.size, 0)  # 'L' significa scala di grigi (0-255)
    draw = ImageDraw.Draw(mask)
    draw.polygon(points, fill=255)  # Disegna il poligono e riempilo con bianco (255)

    # Applica la maschera all'immagine originale
    result = Image.new("RGBA", image.size)  # Creare un'immagine con canale alpha
    result.paste(image, mask=mask)  # Applica la maschera per conservare solo il poligono

    # Ritaglia l'immagine al bounding box del poligono per risparmiare spazio
    x_coords, y_coords = zip(*points)
    x_min, x_max = min(x_coords), max(x_coords)
    y_min, y_max = min(y_coords), max(y_coords)
    result_cropped = result.crop((x_min, y_min, x_max, y_max))

    # Salva l'immagine ritagliata
    image_name = os.path.basename(image_path).split('.')[0]
    output_path = os.path.join(output_dir, f"{image_name}_cropped.png")
    result_cropped.save(output_path)
    print(f"Immagine salvata: {output_path}")

import google.colab.drive
google.colab.drive.mount('/content/drive')

# Specifica la directory delle immagini e la directory di output
input_dir = "/content/Kenya/"
output_dir = "/content/cropped_images"
os.makedirs(output_dir, exist_ok=True)

# Itera attraverso tutte le immagini nella directory

for filename in os.listdir(input_dir):
    if filename.lower().endswith(('.jpg')):  # Filtra per immagini jpg
        image_path = os.path.join(input_dir, filename)
        crop_image_with_polygon(image_path, polygon_points, output_dir)

print("Elaborazione completata!")