# -*- coding: utf-8 -*-
"""meteostat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hJvBERdUtQZzxx5hepvmK2FH1HNGEDtE

#Meteostat rifatto
"""

!pip install meteostat

# Import Meteostat library
from meteostat import Stations
import pandas as pd

# Catalog of regions
catalog = {
    "Namibia": {
        "lat": -28.038970,
        "lon": 18.105889
    },
    "Namibia_Desert": {
        "lat": -26.6446901,
        "lon": 16.0803984
    },
    "Namibia_Savanna": {
        "lat": -24.9229818,
        "lon": 15.8887668
    },
    "Angola": {
        "lat": -16.949631,
        "lon": 12.332528
    },
    "Saudi_Arabia": {
        "lat": 29.6369064,
        "lon": 38.6245267
    },
    "Kenya": {
        "lat": -1.346889,
        "lon": 36.860099
    },
    "Australia_Mulga": {
        "lat": -23.5358481,
        "lon": 119.8517412
    },
    "Australia_Western": {
        "lat": -23.4186270,
        "lon": 119.8371248
    },
    "Australia_Western_Mulga": {
        "lat": -23.360976,
        "lon": 19.955787
    },
    "Niger": {
        "lat": 15.7289412,
        "lon": 9.0080611
    },
    "Niger_Savanna": {
        "lat": 16.6374777,
        "lon": 6.2709376
    },
    "Chad": {
        "lat": 15.827323,
        "lon": 20.147305
    }
}

import pandas as pd
from meteostat import Stations

# DataFrame per raccogliere le informazioni delle stazioni
stations_list = []

# Itera su ciascuna località
for region, coordinates in catalog.items():
    lat = coordinates["lat"]
    lon = coordinates["lon"]
    nome_regione = region
    print(f"Processing: {nome_regione}...")

    # Trova la stazione più vicina
    stations = Stations()
    station = stations.nearby(lat, lon)
    nearby_stations = station.fetch(1)  # Limita alla prima stazione

    if not nearby_stations.empty:
        # Ottieni informazioni sulla stazione
        station_info = nearby_stations.iloc[0]
        station_info["region"] = nome_regione
        station_info = station_info.drop(["country", "wmo", "hourly_end", "hourly_start","monthly_start", "monthly_end", "distance"])
        # Concatena i risultati
        stations_list.append(station_info)

    else:
        print(f"No station found for {nome_regione}")

# Creazione del DataFrame
stations_df = pd.DataFrame(stations_list)

# Salva il DataFrame in un file CSV (opzionale)
stations_df.to_csv("stations_df.csv", index=False)

from meteostat import Daily
from datetime import datetime

# DataFrame per raccogliere i dati climatici
climate_data = pd.DataFrame()

# Itera su ciascuna riga di stations_df
for _, row in stations_df.iterrows():
    if pd.notnull(row["daily_start"]) and pd.notnull(row["daily_end"]):
        nome_regione = row['region']
        station_id = row.name  # Nome della stazione (ID)

        # Convertire le date di inizio e fine in oggetti datetime
        daily_start = row['daily_start']
        daily_end = row['daily_end']

    # Controllare che le date siano valide
    if pd.notnull(daily_start) and pd.notnull(daily_end):

        start = daily_start.to_pydatetime()
        end = daily_end.to_pydatetime()

        start_tuple = (start.year, start.month, start.day)
        end_tuple = (end.year, end.month, end.day)

        start_div = datetime(start_tuple[0], start_tuple[1], start_tuple[2])
        end_div = datetime(end_tuple[0], end_tuple[1], end_tuple[2])

        # Recuperare i dati giornalieri
        data = Daily(station_id, start_div, end_div)
        data = data.fetch()
        data["region"] = nome_regione
        data["start_date"] = daily_start
        data["end_date"] = daily_end

        # Seleziona solo le colonne richieste
        data = data[["region", "start_date", "end_date", "tavg", "tmin", "tmax", "wdir", "wspd", "pres"]].fillna(0)

        # Concatena i dati
        climate_data = pd.concat([climate_data, data])

# Salva i dati climatici in un file CSV
climate_data.to_csv("climate_data.csv", index=False)

"""#Openmeteopy"""

!pip install git+https://github.com/m0rp43us/openmeteopy

import openmeteopy
from openmeteopy import OpenMeteo
from openmeteopy.hourly import HourlyHistorical
from openmeteopy.daily import DailyHistorical
from openmeteopy.options import HistoricalOptions
from openmeteopy.utils.constants import *
import time

# Date range
start_date = "2020-11-29"
end_date = "2020-11-30"

# Iterate through the catalog
for region, coordinates in catalog.items():
    latitude = coordinates["lat"]
    longitude = coordinates["lon"]

    # Set up OpenMeteo request
    hourly = HourlyHistorical()
    daily = DailyHistorical()
    options = HistoricalOptions(
        latitude,
        longitude,
        start_date=start_date,
        end_date=end_date
    )

    #mgr = OpenMeteo(options, hourly.all(), daily.all())
    mgr = OpenMeteo(options, None, daily.all())

    # Download data
    meteo = mgr.get_pandas()
    meteo_df = meteo[0]

    # Save to CSV
    file_name = f"{region}_meteo_data.csv"
    meteo_df.to_csv(file_name, index=False)
    print(f"Data for {region} saved to {file_name}")

    # Add a delay to avoid exceeding the rate limit
    time.sleep(60) # Wait for 60 seconds before the next request